//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassIsland.Assets.Localization.SettingsPage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization_SettingsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_SettingsPage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassIsland.Assets.Localization.SettingsPage.Localization.SettingsPage", typeof(Localization_SettingsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 ClassIsland 的本地化字符串。
        /// </summary>
        public static string About_string {
            get {
                return ResourceManager.GetString("About_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string Appearance_string {
            get {
                return ResourceManager.GetString("Appearance_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动化 的本地化字符串。
        /// </summary>
        public static string Automation_string {
            get {
                return ResourceManager.GetString("Automation_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行为 的本地化字符串。
        /// </summary>
        public static string Behavior_string {
            get {
                return ResourceManager.GetString("Behavior_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件 的本地化字符串。
        /// </summary>
        public static string Components_string {
            get {
                return ResourceManager.GetString("Components_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建快捷换课图标 的本地化字符串。
        /// </summary>
        public static string CreateQuickAdjustCourseShortcut_string {
            get {
                return ResourceManager.GetString("CreateQuickAdjustCourseShortcut_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试窗口规则 的本地化字符串。
        /// </summary>
        public static string DebuggingWindowRules_string {
            get {
                return ResourceManager.GetString("DebuggingWindowRules_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验性功能 的本地化字符串。
        /// </summary>
        public static string ExperimentalFeature_string {
            get {
                return ResourceManager.GetString("ExperimentalFeature_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出诊断数据 的本地化字符串。
        /// </summary>
        public static string ExportDiagData_string {
            get {
                return ResourceManager.GetString("ExportDiagData_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本 的本地化字符串。
        /// </summary>
        public static string General_string {
            get {
                return ResourceManager.GetString("General_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入管理... 的本地化字符串。
        /// </summary>
        public static string JoinManagement_string {
            get {
                return ResourceManager.GetString("JoinManagement_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集控选项 的本地化字符串。
        /// </summary>
        public static string ManagementOptions_string {
            get {
                return ResourceManager.GetString("ManagementOptions_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知 的本地化字符串。
        /// </summary>
        public static string Notification_string {
            get {
                return ResourceManager.GetString("Notification_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开应用目录... 的本地化字符串。
        /// </summary>
        public static string OpenAppDir_string {
            get {
                return ResourceManager.GetString("OpenAppDir_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开数据目录... 的本地化字符串。
        /// </summary>
        public static string OpenDataDir_string {
            get {
                return ResourceManager.GetString("OpenDataDir_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志目录... 的本地化字符串。
        /// </summary>
        public static string OpenLogDir_string {
            get {
                return ResourceManager.GetString("OpenLogDir_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClassIsland 是开源免费的软件，官方没有提供任何形式的付费支持服务，源代码仓库地址在{sourcecodeurl}。如果您通过有偿协助等付费方式取得本应用，在遇到问题时请在与卖家约定的服务框架下，优先向卖家求助。如果卖家没有提供您预期的服务，请退款或通过其它形式积极维护您的合法权益。 的本地化字符串。
        /// </summary>
        public static string OpenSourceStatement {
            get {
                return ResourceManager.GetString("OpenSourceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件 的本地化字符串。
        /// </summary>
        public static string Plugins_string {
            get {
                return ResourceManager.GetString("Plugins_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐私 的本地化字符串。
        /// </summary>
        public static string Privacy_string {
            get {
                return ResourceManager.GetString("Privacy_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启至恢复模式 的本地化字符串。
        /// </summary>
        public static string RestartToRecoveryMode_string {
            get {
                return ResourceManager.GetString("RestartToRecoveryMode_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储 的本地化字符串。
        /// </summary>
        public static string Storage_string {
            get {
                return ResourceManager.GetString("Storage_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Theme_string {
            get {
                return ResourceManager.GetString("Theme_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用设置 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update_string {
            get {
                return ResourceManager.GetString("Update_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志... 的本地化字符串。
        /// </summary>
        public static string ViewAppLog_string {
            get {
                return ResourceManager.GetString("ViewAppLog_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天气 的本地化字符串。
        /// </summary>
        public static string Weather_string {
            get {
                return ResourceManager.GetString("Weather_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        public static string Window_string {
            get {
                return ResourceManager.GetString("Window_string", resourceCulture);
            }
        }
    }
}
