name: Bug 反馈
description: 在使用 ClassIsland 的过程中遇到了Bug。
title: "[Bug]: 在这里输入你的标题"
labels: ["bug"]
assignees: HelloWRC
body:
  - type: markdown
    attributes:
      value: |
        感谢您进行Bug反馈。反馈时请在上面的文本框⬆️起一个能够清晰描述您的问题的标题，便于开发者解决您的问题。**不要删掉开头的“[Bug]: ”。**
        
        如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》（[链接](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)）。
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在开始反馈这个问题之前，请先检查：
      options:
        - label: 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。 
          required: true
        - label: 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
          required: true
        - label: 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
          required: true
        - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）
          required: true
  - type: markdown
    attributes: 
      value: |
        ## Bug 信息

        描述您遇到的 Bug。您可以附上截图、录屏、堆栈跟踪、日志等材料，便于开发者追踪问题。
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我们需要执行哪些操作才能让 bug 出现？
        简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。
      placeholder: |
        1. 首先……
        2. 然后……
        3. ……
    validations:
      required: true
  - type: textarea
    id: excepted
    attributes:
      label: 期望的行为
      description: 详细的描述你期望发生的行为，突出与目前（可能不正确的）行为的不同。
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 实际结果
      description: 实际发生的行为。
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: 堆栈跟踪（可选）
      description: 如果在遇到这个bug时发生了崩溃（弹出崩溃提示），或者产生了错误日志，请将产生的堆栈跟踪信息粘贴到此处，便于定位bug。
      render: shell
  - type: markdown
    attributes:
      value: |
        ## 环境信息
        
        > 如果您是从 ClassIsland 应用本体打开的这个页面，下面的字段可能已经自动填写。
  - type: input
    id: app_version
    attributes:
      label: 应用版本
      description: 您当前使用的ClassIsland版本号，可以在【应用设置】->【关于】中查看。
      placeholder: 如：1.3.2.0-Firefly-e921904(dev)
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: 操作系统版本
      description: 您当前使用的Windows操作系统版本，可以运行 `winver.exe` 查看。
      placeholder: 如：10.0.22000.0

  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步
      description: 回顾您的回答
      options:
        - label: 我认为上述的描述已经足以详细，以允许开发人员能复现该问题
          required: true