using Microsoft.CodeAnalysis;

namespace ClassIsland.SimpleGitInfoGenerator;

[Generator]
public class GitInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 从 MSBuild 属性中获取 Git 信息
        var gitHash = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
        {
            options.GlobalOptions.TryGetValue("build_property.GitCommitHash", out var hash);
            options.GlobalOptions.TryGetValue("build_property.GitBranch", out var branch);
            options.GlobalOptions.TryGetValue("build_property.GitTag", out var tag);
            return (Hash: hash ?? "Unknown", Branch: branch ?? "Unknown", Tag: tag ?? "0.0.0.0");
        });

        // 生成代码
        context.RegisterSourceOutput(gitHash, (spc, info) =>
        {
            var source = $$"""
                           // <auto-generated>
                           
                           namespace ClassIsland
                           {
                               internal static class GitInfo
                               {
                                   public const string CommitHash = "{{info.Hash}}";
                                   public const string Branch = "{{info.Branch}}";
                                   public const string Tag = "{{info.Tag}}";
                               }
                           }
                           """;
            spc.AddSource("GitInfo.g.cs", source);
        });
    }
}