using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentIconsMappingGenerator;

[Generator]
public class FluentIconsMappingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFileProvider = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, _) =>
            {
                var (additionalFile, optionsProvider) = pair;
                var fileOptions = optionsProvider.GetOptions(additionalFile);
                fileOptions.TryGetValue("build_property.FluentIconMappingFile", out var filePath);

                return new
                {
                    File = additionalFile,
                    Options = new GenerateOptions(FilePath: filePath ?? "")
                };
            })
            .Where(tuple =>
            {
                if (string.IsNullOrWhiteSpace(tuple.Options.FilePath) ||
                    string.IsNullOrWhiteSpace(tuple.File.Path))
                    return false;

                var expectedNorm = tuple.Options.FilePath.Replace('\\', '/');
                var actualNorm = tuple.File.Path.Replace('\\', '/');
                return actualNorm.EndsWith(expectedNorm, StringComparison.OrdinalIgnoreCase);
            });

        context.RegisterSourceOutput(jsonFileProvider, (spc, input) =>
        {
            var additionalFile = input.File;
            var options = input.Options;

            var sourceText = additionalFile.GetText();
            if (sourceText == null)
            {
                var diagnostic = Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "FMG001",
                        "Cannot read mapping file",
                        "无法读取图标映射文件 '{0}'",
                        "FluentIconsMappingGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None,
                    additionalFile.Path);
                spc.ReportDiagnostic(diagnostic);
                return;
            }

            var jsonContent = sourceText.ToString();
            var icons = ParseIcons(jsonContent);

            var fiClassCode = GenerateIconsClass(icons, "FluentIcons");
            spc.AddSource("FluentIcons.g.cs", SourceText.From(fiClassCode, Encoding.UTF8));

            var enumCode = GenerateIconKindEnum(icons, "FluentIconKind");
            spc.AddSource("FluentIcon.g.cs", SourceText.From(enumCode, Encoding.UTF8));
        });
    }

    private List<(string Key, string Name, int CodePoint)> ParseIcons(string jsonContent)
    {
        return HardDecoder.ParseJson(jsonContent).Select(prop => (
                                                             prop.Key, 
                                                             prop.Key.Replace("ic_fluent_", "")
                                                                 .Replace("_20_", "_"),
                                                             prop.Value)).ToList();
    }

    private string GenerateIconsClass(List<(string Key, string Name, int CodePoint)> icons, string className)
    {
        var sb = new StringBuilder();
        sb.AppendLine($$"""
                        // <auto-generated/>
                        namespace ClassIsland.Core.Icons 
                        {
                            /// <summary>
                            /// {{className}} 常量池
                            /// </summary>
                            public static class {{className}} 
                            {
                        """);

        foreach (var (key, name, codePoint) in icons)
        {
            sb.AppendLine($$"""
                                    /// <summary>
                                    /// {{key}}
                                    /// </summary>
                                    public const string {{name}} = "\u{{codePoint:X4}}";
                                    
                            """);
        }

        sb.AppendLine("""
                            }
                      }
                      """);
        return sb.ToString();
    }

    private string GenerateIconKindEnum(List<(string Key, string Name, int CodePoint)> icons, string enumName)
    {
        var sb = new StringBuilder();
        sb.AppendLine($$"""
                      // <auto-generated/>
                      namespace ClassIsland.Core.Icons
                      {
                            /// <summary>
                            /// {{enumName}} 枚举
                            /// </summary>
                            public enum {{enumName}}
                            {
                      """);

        foreach (var (key, name, codePoint) in icons)
        {
            sb.AppendLine($"""
                                    /// <summary>
                                    /// {key}
                                    /// </summary>
                                    {name} = {codePoint},
                            """);
        }

        sb.AppendLine("""
                            }
                      }
                      """);
        return sb.ToString();
    }
}