using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentIconsMappingGenerator;

[Generator]
public class FluentIconsMappingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFileProvider = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, _) =>
            {
                var (additionalFile, optionsProvider) = pair;
                var fileOptions = optionsProvider.GetOptions(additionalFile);
                fileOptions.TryGetValue("build_property.FluentIconMappingFile", out var filePath);

                return new
                {
                    File = additionalFile,
                    Options = new GenerateOptions(FilePath: filePath ?? "")
                };
            })
            .Where(tuple =>
            {
                if (string.IsNullOrWhiteSpace(tuple.Options.FilePath) ||
                    string.IsNullOrWhiteSpace(tuple.File.Path))
                    return false;

                var expectedNorm = tuple.Options.FilePath.Replace('\\', '/');
                var actualNorm = tuple.File.Path.Replace('\\', '/');
                return actualNorm.EndsWith(expectedNorm, StringComparison.OrdinalIgnoreCase);
            });

        context.RegisterSourceOutput(jsonFileProvider, (spc, input) =>
        {
            var additionalFile = input.File;
            var options = input.Options;

            var sourceText = additionalFile.GetText();
            if (sourceText == null)
            {
                var diagnostic = Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "FMG001",
                        "Cannot read mapping file",
                        "无法读取图标映射文件 '{0}'",
                        "FluentIconsMappingGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None,
                    additionalFile.Path);
                spc.ReportDiagnostic(diagnostic);
                return;
            }

            var jsonContent = sourceText.ToString();
            var icons = ParseIcons(jsonContent);

            var fiClassCode = GenerateFluentIconsClass(icons);
            spc.AddSource("FluentIcons.g.cs", SourceText.From(fiClassCode, Encoding.UTF8));

            var enumCode = GenerateFluentIconKindEnum(icons);
            spc.AddSource("FluentIcon.g.cs", SourceText.From(enumCode, Encoding.UTF8));
        });
    }

    private List<(string Key, string Name, int CodePoint)> ParseIcons(string jsonContent)
    {
        using var doc = JsonDocument.Parse(jsonContent);
        
        return doc.RootElement.EnumerateObject()
            .Select(prop =>
            {
                // ic_fluent_access_time_20_regular → access_time_regular
                var name = prop.Name
                    .Replace("ic_fluent_", "")
                    .Replace("_20_", "_");
                var codePoint = prop.Value.GetInt32();
                return (prop.Name, name, codePoint);
            })
            .ToList();
    }

    private string GenerateFluentIconsClass(List<(string Key, string Name, int CodePoint)> icons)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace ClassIsland.Core.Icons");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// FluentIcon 常量池");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class FluentIcons");
        sb.AppendLine("    {");

        foreach (var (key, name, codePoint) in icons)
        {
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// {key}");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public const string {name} = \"\\u{codePoint:X4}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateFluentIconKindEnum(List<(string Key, string Name, int CodePoint)> icons)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace ClassIsland.Core.Icons");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// FluentIcon 种类");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public enum FluentIconKind");
        sb.AppendLine("    {");

        foreach (var (key, name, codePoint) in icons)
        {
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// {key}");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        {name} = {codePoint},");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}